apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dotnet-deployment
  labels:
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: dotnet-deployment
    spec:
      containers:
        - name: dotnet
          image: k8sdemoregistory.azurecr.io/k8sdemoregistory:#{tag}#
          imagePullPolicy: Always
          name: dotnet-deployment
          ports:
          - containerPort: 80
      imagePullSecrets:
        - name: acr-secret
