apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-deployment
  labels:
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dotnet-deployment  
  template:
    metadata:
      labels:
        app: dotnet-deployment
    spec:
      containers:
        - name: dotnet
          image: k8sdemoregistory.azurecr.io/kcsakashpreetaspnet:#{Build.BuildNumber}#
          imagePullPolicy: Always
          name: dotnet-deployment
          ports:
          - containerPort: 80
      imagePullSecrets:
        - name: acr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: dotnet-deployment
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: dotnet-deployment
  type: LoadBalancer
