apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dotnet-deployment
  labels:
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: dotnet-deployment
    spec:
      containers:
        - name: dotnet
          image: k8sdemoregistory.azurecr.io/kcsakashpreetaspnet:#{tag}#
          imagePullPolicy: Always
          name: dotnet-deployment
          ports:
          - containerPort: 80
      imagePullSecrets:
        - name: acr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: dotnet-deployment
spec:
  ports:
  - port: 80
    protocol: TCP
  #selector:
    #run: httpd-deployment
  selector:
    app: dotnet-deployment
  selector:
    app: dotnet-deployment
  type: LoadBalancer
