apiVersion: v1
kind: Service
metadata:
  name: dotnet-deployment
spec:
  ports:
  - port: 80
    protocol: TCP
  #selector:
    #run: httpd-deployment
  selector:
    app: dotnet-deployment
  selector:
    app: dotnet-deployment
  type: LoadBalancer
